spring.application.name=application_service

server.port=8084
server.servlet.context-path=/application

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}

spring.jpa.hibernate.ddl-auto=update