spring.application.name=company_service

server.port=8082
server.servlet.context-path=/company

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}

spring.jpa.hibernate.ddl-auto=update

# Enable CORS globally
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
