spring.application.name=job_service

server.port=8083
server.servlet.context-path=/job

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

spring.jpa.hibernate.ddl-auto=update